


LIB_SOURCES := 	src/builtinFunctions.c \
			src/base64.c \
			src/cookie.c src/convert.c \
			src/conditions.c src/engine.c \
			src/engine_parser.c \
			src/engine_functions.c \
			src/engine_api_extensions.c \
			src/engine_if.c \
			src/engine_tags.c \
			src/file_manager.c \
			src/globals.c \
			src/header.c \
			src/header_parser.c \
			src/header_send.c \
			src/linked_list.c \
			src/message_queue.c \
			src/reverse_proxy.c \
			src/server.c \
			src/server_chunk_functions.c \
			src/server_config.c \
			src/server_error_pages.c \
			src/session.c \
			src/sha1.c \
			src/system.c \
			src/system_memory.c \
			src/system_memory_gcc.c \
			src/system_sockets.c \
			src/system_sockets_recv.c \
			src/system_sockets_send.c \
			src/system_sockets_container.c \
			src/system_sockets_events.c \
			src/system_sockets_select.c \
			src/system_sockets_epoll.c \
			src/system_file_access.c \
			src/system_file_access_utils.c \
			src/system_file_access_fs.c \
			src/system_file_access_binary.c \
			src/system_file_access_wnfs.c \
			src/system_file_cache.c \
			src/webserver_api_functions.c \
			src/utils.c \
			src/hashmap.c \
			src/log.c \
			src/variable.c \
			src/variable_global.c \
			src/variable_store.c \
			src/variable_render.c \
			src/websockets.c \
			src/websockets_send_recv.c \
			src/websockets_streaming.c \
			src/websocket_handler.c \
			ssl/openssl.c \
			ssl/mbedtls2.c \
			ssl/mbedtls3.c \
			ssl/wolfssl.c \
			python/py_utils.c \
			python/py_plugin.c \
			python/py_api_functions.c \
			platform/platform-file-access.c \
			platform/platform-sockets.c \
			platform/platform.c 

TP_SOURCES	:= 	third_party/src/rb_tree/red_black_tree.c third_party/src/rb_tree/misc.c third_party/src/rb_tree/stack.c \
			third_party/src/is_utf8/is_utf8.c \
			third_party/src/miniz/miniz.c




SOURCES := $(LIB_SOURCES) $(TP_SOURCES)
#			$(MBEDTLS)
